name: Trigger Playwright Tests Before Merge

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  # Esto activará el workflow cuando un PR se cree hacia la rama main.

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Playwright Tests
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/ul-ernestomolina/tafrepo/dispatches \
               -d '{"event_type": "run_playwright_tests", "client_payload": { "branch": "main" }}'

  wait-for-results:
    needs: trigger-tests
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Test Results
        run: |
          while true; do
            STATUS=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  https://api.github.com/repos/ul-ernestomolina/tafrepo/actions/runs \
                  | jq -r '.workflow_runs | sort_by(.created_at) | reverse | .[0].conclusion')

            echo "Test Status: $STATUS"

            if [[ "$STATUS" == "success" ]]; then
              echo "✅ Tests Passed!"
              exit 0
            elif [[ "$STATUS" == "failure" ]]; then
              echo "❌ Tests Failed!"
              exit 1
            fi
            sleep 10
          done
